import React from 'react';
import { motion } from 'framer-motion';
import { Card } from '../ui/Card';
import { Skeleton } from '../ui/Skeleton';

interface ContentPreviewProps {
  content: string;
  isLoading?: boolean;
  model?: string;
  provider?: string;
}

export const ContentPreview: React.FC<ContentPreviewProps> = ({
  content,
  isLoading,
  model,
  provider,
}) => {
  if (isLoading) {
    return (
      <Card glass>
        <div className="space-y-3">
          <Skeleton className="h-4 w-3/4" />
          <Skeleton className="h-4 w-full" />
          <Skeleton className="h-4 w-5/6" />
          <Skeleton className="h-4 w-4/5" />
        </div>
      </Card>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
    >
      <Card glass>
        {model && provider && (
          <div className="mb-3 text-sm text-gray-600 dark:text-gray-400">
            Generated by <span className="font-semibold text-blue-500">{model}</span> ({provider})
          </div>
        )}
        <div className="prose max-w-none dark:prose-invert">
          <motion.pre
            className="whitespace-pre-wrap font-sans text-sm text-gray-900 dark:text-gray-100"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.2 }}
          >
            {content || 'No content generated yet. Configure and generate to see preview.'}
          </motion.pre>
        </div>
      </Card>
    </motion.div>
  );
};

