import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { motion } from 'framer-motion';
import { Card } from '../ui/Card';
import { Skeleton } from '../ui/Skeleton';
export const ContentPreview = ({ content, isLoading, model, provider, }) => {
    if (isLoading) {
        return (_jsx(Card, { glass: true, children: _jsxs("div", { className: "space-y-3", children: [_jsx(Skeleton, { className: "h-4 w-3/4" }), _jsx(Skeleton, { className: "h-4 w-full" }), _jsx(Skeleton, { className: "h-4 w-5/6" }), _jsx(Skeleton, { className: "h-4 w-4/5" })] }) }));
    }
    return (_jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.3 }, children: _jsxs(Card, { glass: true, children: [model && provider && (_jsxs("div", { className: "mb-3 text-sm text-gray-600 dark:text-gray-400", children: ["Generated by ", _jsx("span", { className: "font-semibold text-blue-500", children: model }), " (", provider, ")"] })), _jsx("div", { className: "prose max-w-none dark:prose-invert", children: _jsx(motion.pre, { className: "whitespace-pre-wrap font-sans text-sm text-gray-900 dark:text-gray-100", initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.2 }, children: content || 'No content generated yet. Configure and generate to see preview.' }) })] }) }));
};
//# sourceMappingURL=ContentPreview.js.map