import { z } from 'zod';
export declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
    PORT: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    FRONTEND_URL: z.ZodDefault<z.ZodString>;
    DATABASE_URL: z.ZodString;
    DB_MAX_CONNECTIONS: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    DB_IDLE_TIMEOUT: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    DB_CONNECT_TIMEOUT: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    REDIS_URL: z.ZodDefault<z.ZodString>;
    JWT_SECRET: z.ZodString;
    JWT_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    REFRESH_TOKEN_SECRET: z.ZodString;
    REFRESH_TOKEN_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    SARVAM_API_KEY: z.ZodOptional<z.ZodString>;
    GROQ_API_KEY: z.ZodOptional<z.ZodString>;
    GEMINI_API_KEY: z.ZodOptional<z.ZodString>;
    DEEPSEEK_API_KEY: z.ZodOptional<z.ZodString>;
    TTS_API_URL: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    TTS_STORAGE_PATH: z.ZodDefault<z.ZodString>;
    MEDIA_STORAGE_PATH: z.ZodDefault<z.ZodString>;
    MEDIA_PUBLIC_URL: z.ZodDefault<z.ZodString>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["error", "warn", "info", "debug"]>>;
    LOGS_DIR: z.ZodDefault<z.ZodString>;
    ENABLE_RATE_LIMITING: z.ZodDefault<z.ZodEffects<z.ZodString, boolean, string>>;
    ENABLE_API_KEYS: z.ZodDefault<z.ZodEffects<z.ZodString, boolean, string>>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "production" | "development" | "test";
    DATABASE_URL: string;
    DB_MAX_CONNECTIONS: number;
    DB_IDLE_TIMEOUT: number;
    DB_CONNECT_TIMEOUT: number;
    JWT_SECRET: string;
    TTS_API_URL: string;
    TTS_STORAGE_PATH: string;
    MEDIA_STORAGE_PATH: string;
    MEDIA_PUBLIC_URL: string;
    LOGS_DIR: string;
    LOG_LEVEL: "error" | "info" | "debug" | "warn";
    PORT: number;
    FRONTEND_URL: string;
    REDIS_URL: string;
    JWT_EXPIRES_IN: string;
    REFRESH_TOKEN_SECRET: string;
    REFRESH_TOKEN_EXPIRES_IN: string;
    ENABLE_RATE_LIMITING: boolean;
    ENABLE_API_KEYS: boolean;
    SARVAM_API_KEY?: string | undefined;
    GROQ_API_KEY?: string | undefined;
    GEMINI_API_KEY?: string | undefined;
    DEEPSEEK_API_KEY?: string | undefined;
}, {
    DATABASE_URL: string;
    JWT_SECRET: string;
    REFRESH_TOKEN_SECRET: string;
    NODE_ENV?: "production" | "development" | "test" | undefined;
    DB_MAX_CONNECTIONS?: string | undefined;
    DB_IDLE_TIMEOUT?: string | undefined;
    DB_CONNECT_TIMEOUT?: string | undefined;
    SARVAM_API_KEY?: string | undefined;
    GROQ_API_KEY?: string | undefined;
    GEMINI_API_KEY?: string | undefined;
    DEEPSEEK_API_KEY?: string | undefined;
    TTS_API_URL?: string | undefined;
    TTS_STORAGE_PATH?: string | undefined;
    MEDIA_STORAGE_PATH?: string | undefined;
    MEDIA_PUBLIC_URL?: string | undefined;
    LOGS_DIR?: string | undefined;
    LOG_LEVEL?: "error" | "info" | "debug" | "warn" | undefined;
    PORT?: string | undefined;
    FRONTEND_URL?: string | undefined;
    REDIS_URL?: string | undefined;
    JWT_EXPIRES_IN?: string | undefined;
    REFRESH_TOKEN_EXPIRES_IN?: string | undefined;
    ENABLE_RATE_LIMITING?: string | undefined;
    ENABLE_API_KEYS?: string | undefined;
}>;
export type EnvConfig = z.infer<typeof envSchema>;
//# sourceMappingURL=schema.d.ts.map